---
  - name: Enable EPEL repo
    yum:
      name: epel-release
      state: latest

  - name: Update the system
    yum:
      name: '*'
      state: latest
    
  - name: Install base packages
    yum:
      name: "{{ base_packages }}"
      state: latest

  - name: Install s3cmd
    pip:
      name: s3cmd
  
  - name: Create the s3cmd configuration file
    template:
      src: templates/s3cfg.j2
      dest: /root/.s3cfg